back ⚙️:
- changed-files:
  - any-glob-to-any-file: back/**

migration 📦:
- changed-files:
  - any-glob-to-any-file: back/Blouppy.Infrastructure/Persistence/Migrations/*

front 👁️:
- changed-files:
  - any-glob-to-any-file: front/**

api 🌐:
- changed-files:
  - any-glob-to-any-file: api/**

ci/cd 🚀:
- changed-files:
  - any-glob-to-any-file: .github/workflows/**

documentation 📄:
  - changed-files:
    - any-glob-to-any-file: docs/**
    - any-glob-to-any-file: README.md
    - any-glob-to-any-file: CONTRIBUTING.md
    - any-glob-to-any-file: CHANGELOG.md