feature 📦:
- changed-files:
  - any-glob-to-any-file: Blouppy.Events/**

test 🧪:
- changed-files:
  - any-glob-to-any-file: Blouppy.Events.Tests/**

ci/cd 🚀:
- changed-files:
  - any-glob-to-any-file: .github/workflows/**

renovate ⚙️:
- changed-files:
  - any-glob-to-any-file: .github/renovate/**

documentation 📄:
  - changed-files:
    - any-glob-to-any-file: docs/**
    - any-glob-to-any-file: README.md
    - any-glob-to-any-file: CONTRIBUTING.md
    - any-glob-to-any-file: CHANGELOG.md